site_url: https://ntn-boilerplate.netlify.app/
logo_url: https://ntn-boilerplate.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'home'
    label: 'Accueil'
    folder: 'content/home'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    # editor:
    #   preview: true
    fields:
      - { label: 'Title 1', name: 'title_1', widget: 'string', required: true }
      - { label: 'Title 2', name: 'title_2', widget: 'string', required: true }
      - { label: 'Description', name: 'description_1', widget: 'string', required: true }
      - { label: 'Description 2', name: 'description_2', widget: 'string', required: true }
      - { label: 'Texte button', name: 'button', widget: 'string', required: true }
      - { label: 'Lien button', name: 'button_link', widget: 'string', required: true }
  - name: 'hours'
    label: 'Horaire'
    folder: 'content/hours'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'hours'
    fields:
      - { label: 'Titre', name: 'title', widget: 'string', required: true }
      - { label: 'Image horaire', name: 'hours', widget: 'image', required: true, allow_multiple: false }
      - { label: 'Texte over', name: 'over', widget: 'string', required: false }
  - name: 'season'
    label: 'Saison'
    folder: 'content/season'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'season'
    fields:
      - { label: 'Titre', name: 'title', widget: 'string', required: true }
      - label: 'Links'
        name: 'link'
        widget: 'list'
        fields:
          - { label: 'Label', name: 'label', widget: 'string', required: true }
          - { label: 'Link', name: 'link', widget: 'string', required: true }
      - { label: 'Team title', name: 'team_title', widget: 'string', required: true }
      - label: 'Teams'
        name: 'teams'
        widget: 'list'
        fields:
          - { label: 'Name', name: 'name', widget: 'string', required: true }
          - { label: 'Description', name: 'description', widget: 'string', required: true }
          - { label: 'Image', name: 'image', widget: 'image', required: true, allow_multiple: false }
